@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Občan\nAdministrator\nUpravljalec predlogov (organizacija)\nUpravljalec novic\nUpravljalec dogodkov" as Neprijavljen <<actor>>
participant "ZMPrijavniObrazec" as Obrazec <<boundary>> #lightBlue
participant "KrmilnikPrijava" as Krmilnik <<control>> #lightGray

Neprijavljen -> Obrazec: 1. zacniPrijavo()
activate Obrazec
Obrazec -> Krmilnik: 2. prijava(req, res)
activate Krmilnik
Krmilnik -> Krmilnik: 3. validacijaAtributov(body)
activate Krmilnik
deactivate Krmilnik
Obrazec <-- Krmilnik: // sporočilo o napačni vnosni vrednosti
deactivate Krmilnik
@enduml