@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white


actor "Občan\nAdministrator\nUpravljalec predlogov (organizacija)\nUpravljalec novic\nUpravljalec dogodkov\nNeprijavljeni uporabnik" as Prijavljen <<actor>>
participant "ZMPodatkiPredlog" as PodatkiPredlog <<boundary>> #lightBlue
participant "ZMSeznamPredlogov" as SeznamPredlogov <<boundary>> #lightBlue
participant "KrmilnikPredloga" as PKrmilnik <<control>> #lightGray
participant “PredlogProjekta” as Predloga <<entity>> #lightYellow 

Prijavljen -> PKrmilnik: 1. seznamPredlogov(req, res)
activate PKrmilnik
PKrmilnik -> Predloga: 2. vrniVsi(req, res)
activate Predloga
PKrmilnik <-- Predloga: // sporočilo OK in seznam vseh predlogov
deactivate Predloga
SeznamPredlogov <-- PKrmilnik: // preusmeri na seznam vseh potrjenih predlogov
deactivate PKrmilnik
activate SeznamPredlogov
SeznamPredlogov -> PKrmilnik: 3. razvrsti(req, res)
activate PKrmilnik
PKrmilnik -> PKrmilnik: 4. razvrstiSeznamPredlogovProjektov(predlogi, akcija)
activate PKrmilnik
deactivate PKrmilnik
SeznamPredlogov <-- PKrmilnik: // vrni posodobljen seznam potrjenih predlogov
deactivate PKrmilnik
@enduml