@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white


actor "Administrator" as Prijavljen <<actor>>
participant "ZMPodatkiPredlog" as PodatkiPredlog <<boundary>> #lightBlue
participant "ZMSeznamPredlogov" as SeznamPredlogov <<boundary>> #lightBlue
participant "ZMUporabniškiProfil" as MojProfil <<boundary>> #lightBlue
participant "KrmilnikUporabnik" as Krmilnik <<control>> #lightGray
participant "KrmilnikPredloga" as PKrmilnik <<control>> #lightGray
participant Uporabnik <<entity>> #lightYellow
participant “PredlogProjekta” as Predloga <<entity>> #lightYellow

Prijavljen -> PKrmilnik: 1. seznamPredlogov(req, res)
activate PKrmilnik
PKrmilnik -> Predloga: 2. vrniVsi(req, res)
activate Predloga
PKrmilnik <-- Predloga: // sporočilo OK in seznam vseh potrjenih predlogov
deactivate Predloga
SeznamPredlogov <-- PKrmilnik: // preusmeri na seznam vseh potrjenih predlogov
deactivate PKrmilnik
activate SeznamPredlogov
SeznamPredlogov -> PKrmilnik: 3. prikaziPredlogProjekta(req, res)
activate PKrmilnik
PKrmilnik -> Predloga: 4. vrniPredlogProjektaID(req, res)
activate Predloga
PKrmilnik <-- Predloga: // sporočilo OK in predlog projekta,\n ki mu pripada izbran ID
deactivate Predloga
PodatkiPredlog <-- PKrmilnik: // preusmeri na obrazec s podatki o predlogu
deactivate PKrmilnik
deactivate SeznamPredlogov
activate PodatkiPredlog
PodatkiPredlog -> Krmilnik: 5. prikaziProfil(req, res)
activate Krmilnik
Krmilnik -> Uporabnik: 6. vrniUporabnikID(req, res)
activate Uporabnik
Krmilnik <-- Uporabnik: // sporočilo OK in uporabnik,\n ki mu pripada izbran ID
deactivate Uporabnik
MojProfil <-- Krmilnik: // preusmeri na uporabniški profil
deactivate Krmilnik
deactivate PodatkiPredlog
activate MojProfil
MojProfil -> MojProfil: 7. odpriObrazecZaUrejanjeProfila()\n// odpre modalno okno
activate MojProfil
MojProfil -> Krmilnik: 8. urediProfil(req, res)
activate Krmilnik
Krmilnik -> Krmilnik: 9. validacijaAtributov(body)
Krmilnik -> Uporabnik: 10. urediUporabnikID(req, res)
activate Uporabnik
Krmilnik <-- Uporabnik: // sporočilo OK in urejen uporabniški profil
deactivate Uporabnik
MojProfil <-- Krmilnik: // prikaži urejen uporabniški profil
deactivate Krmilnik
deactivate MojProfil
@enduml