@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

actor "Neregistrirani uporabnik" as Neregistriran <<actor>>
participant "ZMPrijavniObrazec" as PObrazec <<boundary>> #lightBlue
participant "ZMRegistracijskiObrazec" as RObrazec <<boundary>> #lightBlue
participant "ZMDomačaStran" as DomacaStran <<boundary>> #lightBlue
participant "KrmilnikRegistracija" as Krmilnik <<control>> #lightGray
participant Uporabnik <<entity>> #lightYellow

Neregistriran -> PObrazec: 1. zacniPrijavo()
activate PObrazec
PObrazec -> RObrazec: 2. zacniRegistracijo()
deactivate PObrazec
activate RObrazec
RObrazec -> Krmilnik: 3. registracija(req, res)
activate Krmilnik
Krmilnik -> Krmilnik: 4. validacijaAtributov(body)
activate Krmilnik
deactivate Krmilnik
Krmilnik -> Uporabnik: 5. dodajUporabnik(req, res)
activate Uporabnik
Uporabnik -> Uporabnik: 6. preveriAtribute(akcija)
activate Uporabnik
deactivate Uporabnik
Krmilnik <-- Uporabnik: // sporočilo OK
deactivate Uporabnik
Krmilnik -> DomacaStran: 7. preusmeriNaDomacoStran()
deactivate Krmilnik
activate DomacaStran
@enduml