@startuml
hide footbox

skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white


actor "Občan\nAdministrator\nUpravljalec predlogov (organizacija)\nUpravljalec novic\nUpravljalec dogodkov\nNeregistrirani uporabnik" as Prijavljen <<actor>>
participant "ZMObčina" as PodatkiObcine <<boundary>>  #lightBlue
participant "KrmilnikObčina" as OKrmilnik <<control>>  #lightGray
participant "Občina" as Obcina <<entity>> #lightYellow

Prijavljen -> OKrmilnik: 1. prikazPodatkiObcine(req, res)
activate OKrmilnik
OKrmilnik -> Obcina: 2. vrniObcinaID(req, res)
activate Obcina
OKrmilnik <-- Obcina: // sporočilo OK in podatki o izbrani občini
deactivate Obcina
PodatkiObcine <-- OKrmilnik: 3. preusmeriNaPodatkeObčini()
deactivate OKrmilnik
activate PodatkiObcine
@enduml