@startuml vse_funkcionalnosti
skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam usecase {
  backgroundColor white
  borderColor #5FB8EC
  arrowColor black
}
skinparam backgroundcolor transparent
skinparam defaultTextAlignment center
skinparam usecase {
  backgroundColor white
  borderColor #5FB8EC
  arrowColor black
}
skinparam actorBorderColor black
skinparam actorBackgroundColor white

left to right direction

actor "Neregistrirani uporabnik" as NeregistraniUporabnik
actor "Občan" as Obcan
actor "Upravljalec predlogov\n(organizacija)" as UpravljalecPredlogov
actor "Upravljalec dogodkov" as UpravljalecDogodkov
actor "Upravljalec novic" as UpravljalecNovic
actor "Administrator" as Administrator
actor "Google Calendar" as GoogleCalendar
actor "Novice" as lokalneNovice
actor "Pomožni akter" as PomozniAkter

rectangle "SLObčina" {
  PomozniAkter -down--> (Ogled novice [PU8])
  PomozniAkter -down--> (Ogled predloga projekta [PU11])
  PomozniAkter -down--> (Ogled podatkov občine [PU13])
  PomozniAkter -down--> (Ogled fotografije [PU19])
  PomozniAkter -down--> (Ogled dogodka [PU23])
  PomozniAkter -down--> (Filtriranje predlogov projektov [PU25])
  PomozniAkter -down--> (Izbira občine [PU26])
  
  NeregistraniUporabnik -down-> (Registracija uporabnika [PU1])
  
  Obcan -down--> (Prijava uporabnika [PU2])
  Obcan -down-> (Odjava uporabnika [PU3])
  Obcan -down-> (Urejanje uporabniškega profila [PU4])
  Obcan -down-> (Dodajanje predloga projekta [PU10])
  Obcan -down-> (Ogled uporabniškega profila [PU15])
  Obcan -down-> (Dodajanje fotografije [PU16])
  Obcan -down-> (Ocenjevanje predloga projekta [PU24])
  Obcan -down-> (Sinhronizacija dogodkov z aplikacijo Google Calendar [PU27])
  

  Administrator -down-> (Prijava uporabnika [PU2])
  Administrator -down-> (Odjava uporabnika [PU3])
  Administrator -down-> (Urejanje uporabniškega profila [PU4])
  Administrator -down-> (Brisanje uporabniškega profila [PU5])
  Administrator -down-> (Urejanje podatkov občine [PU14])
  Administrator -down-> (Ogled uporabniškega profila [PU15])
  Administrator -down-> (Dodajanje fotografije [PU16])
  Administrator -down-> (Brisanje fotografije [PU18])

  UpravljalecPredlogov -down-> (Prijava uporabnika [PU2])
  UpravljalecPredlogov -down-> (Odjava uporabnika [PU3])
  UpravljalecPredlogov -down-> (Urejanje uporabniškega profila [PU4])
  UpravljalecPredlogov -down-> (Urejanje predloga projekta [PU12])
  UpravljalecPredlogov -down-> (Ogled uporabniškega profila [PU15])
  
  UpravljalecNovic -down-> (Prijava uporabnika [PU2])
  UpravljalecNovic -down-> (Odjava uporabnika [PU3])
  UpravljalecNovic -down-> (Urejanje uporabniškega profila [PU4])
  UpravljalecNovic -down-> (Dodajanje novice [PU6])
  UpravljalecNovic -down-> (Urejanje novice [PU7])
  UpravljalecNovic -down-> (Brisanje novice [PU9])
  UpravljalecNovic -down-> (Ogled uporabniškega profila [PU15])
  
  UpravljalecDogodkov -down-> (Prijava uporabnika [PU2])
  UpravljalecDogodkov -down-> (Odjava uporabnika [PU3])
  UpravljalecDogodkov -down-> (Urejanje uporabniškega profila [PU4])
  UpravljalecDogodkov -down-> (Ogled uporabniškega profila [PU15])
  UpravljalecDogodkov -down-> (Urejanje dogodka [PU20])
  UpravljalecDogodkov -down-> (Brisanje dogodka [PU21])
  UpravljalecDogodkov -down-> (Dodajanje dogodka [PU22])
  UpravljalecDogodkov -down-> (Sinhronizacija dogodkov z aplikacijo Google Calendar [PU27])
   
  GoogleCalendar <-up- (Sinhronizacija dogodkov z aplikacijo Google Calendar [PU27])
  GoogleCalendar <-up- (Ogled dogodka [PU23])
  GoogleCalendar <-up- (Urejanje dogodka [PU20])
  GoogleCalendar <-up- (Brisanje dogodka [PU21])
  GoogleCalendar <-up- (Dodajanje dogodka [PU22])

  lokalneNovice -up-> (Dodajanje novice [PU6])
  lokalneNovice -up-> (Urejanje novice [PU7])
  lokalneNovice -up-> (Ogled novice [PU8])
  lokalneNovice -up-> (Brisanje novice [PU9])
  
  UpravljalecDogodkov -down-|> PomozniAkter
  UpravljalecNovic -down-|> PomozniAkter
  UpravljalecPredlogov -down-|> PomozniAkter
  Obcan -down-|> PomozniAkter
  Administrator -down-|> PomozniAkter
  NeregistraniUporabnik -down-|> PomozniAkter

}
@enduml