@startuml
skinparam Class {
  backgroundColor white
  borderColor #5FB8EC
  arrowColor black
}
skinparam linetype ortho
skinparam backgroundcolor transparent
skinparam nodesep 100
skinparam ranksep 100
hide circle
Class "ZMSeznamUporabnikov" as ZMSeznamUporabnikov <<boundary>> #lightBlue {
}

Class "ZMUporabniškiProfil" as ZMUporabniskiProfil <<boundary>> #lightBlue {
  +odpriObrazecZaUrejanjeProfila(): void
}

Class "ZMDomačaStran" as ZMDomacaStran <<boundary>> #lightBlue {
  +preusmeriNaDomacoStran(): void
  +prikazDomacaStran(): void
}

Class "KrmilnikUporabnik" as KrmilnikUporabnik <<control>> #lightGray {
  +seznamUporabnikov(Object req, Object res): void
  +urediProfil(Object req, Object res): void
  +izbrisiProfil(Object req, Object res): void
  +prikaziProfil(Object req, Object res): void
  +validacijaAtributov(Object body): boolean
}

Class "Uporabnik" as Uporabnik <<entity>> #lightYellow {
  -id: string
  -ime: string
  -priimek: string
  -hashGeslo: string
  -key: string
  -slikaUporabnika: Slika[]
  -email: string
  -telefonskaStevilka: string
  -rojstniDatum: date
  -naslov: string
  -mesto: string
  -obcina: Obcina[]
  -opis: string
  -registriranOd: date
  -vloga: string
  -predlogi: Predlog[]
  -novice: Novica[]
  -organizacije: Organizacija[]
  --
  +dodajUporabnik(Object req, Object res): void
  +vrniUporabnik(Object req, Object res): void
  +preveriAtribute(Object akcija): boolean
  +vrniVsi(Object req, Object res): void
  +vrniUporabnikID(Object req, Object res): void
  +urediUporabnikID(Object req, Object res): void
  +izbrisiUporabnikID(Object req, Object res): void
}

ZMSeznamUporabnikov "1..1 " -right-> "     1..1" KrmilnikUporabnik
ZMUporabniskiProfil "1..1 " -right-> "     1..1" KrmilnikUporabnik
KrmilnikUporabnik "0..1 " -down-> "     0..*" Uporabnik
@enduml