@startuml
skinparam Class {
  backgroundColor white
  borderColor #5FB8EC
  arrowColor black
}
skinparam linetype ortho
skinparam backgroundcolor transparent
skinparam nodesep 100
skinparam ranksep 100
hide circle



Class "ZMPodatkiPredlog" as ZMPodatkiPredlog <<boundary>> #lightBlue {
 +odpriObrazec(): void
}

Class "ZMSeznamPredlogov" as ZMSeznamPredlogov <<boundary>> #lightBlue {
  +odpriObrazecZaDodajanjePredlogaProjekta(): void
}

Class "KrmilnikPredloga" as KrmilnikPredloga <<control>> #lightGray {
  +seznamPredlogov(Object req, Object res): void
  +prikaziPredlogProjekta(Object req, Object res): void
  +shraniPredlogProjekta(Object req, Object res): void
  +validacijaAtributov(Object body): boolean
  +spremeniStatusPredlogProjekta(Object req, Object res): void
  +vrniNajPriljubljeni(Object req, Object res): void
  +oceniPredlogProjekta(Object req, Object res): void
  +filtrirajSeznamPredlogovProjektov(Object req, Object res): void
  +razvrstiSeznamPredlogovProjektov(Predlog[] predlogi, string akcija): void
  +razvrsti(Object req, Object res): void
}

Class "PredlogProjekta" as PredlogProjekta <<entity>> #lightYellow {
  -id: string
  -naslov: string
  -sporocilo: string
  -razred: string
  -jePotrjen: boolean
  -datum: date
  -ocene: Ocena[]
  --
  +vrniVsi(Object req, Object res): void
  +vrniPredlogProjektaID(Object req, Object res): void
  +urediPredlogProjektaID(Object req, Object res): void
  +dodajPredlogProjekta(): void
  +vrniVsiFilter(Object req, Object res): void
}

ZMPodatkiPredlog "1..1 " -right-> " 1..1" KrmilnikPredloga
ZMSeznamPredlogov "1..1 " -right-> " 1..1" KrmilnikPredloga
KrmilnikPredloga "0..1 " -down-> " 0..*" PredlogProjekta
@enduml