@startuml
skinparam Class {
  backgroundColor white
  borderColor #5FB8EC
  arrowColor black
}
skinparam linetype ortho
skinparam backgroundcolor transparent
skinparam nodesep 100
skinparam ranksep 100
hide circle

Class "ZMPrijavniObrazec" as ZMPrijavniObrazec <<boundary>> #lightBlue {
  +zacniPrijavo(): void
}

Class "KrmilnikPrijava" as KrmilnikPrijava <<control>> #lightGray {
  +prijava(Object req, Object res): void
  +validacijaAtributov(Object body): boolean
  +odjava(Object req, Object res): void
}

ZMPrijavniObrazec "1..1 " -right-> "     1..1" KrmilnikPrijava
@enduml